### PR TITLE
Add support for creating outbound emails

### PR DESCRIPTION
**Pull request by sorrison**
See https://developer.freshdesk.com/api/#create_outbound_email

### CODE REVIEW

**Comment by intellisense** [comment]
Hi, any plans on merging this PR and creating a new release on pypi?

**Comment by sorrison** [comment]
Yeah would be great if this could be merged

**Comment by sjkingo** [comment]
Sorry guys I've been away. I'll try and get it merged and released very shortly.

**Comment by sjkingo** [comment]
Apologies for the delay. Merged and released on PyPi as 1.1.0 now.

**Pull request merged**
