### PR TITLE
Added creating tickets api

### PR DESCRIPTION
**Pull request by silentninja**
Added a post method and creating tickets api

### CODE REVIEW

**Comment by sjkingo** [comment]
Could you provide some tests for this addition? You can find the test file in `freshdesk/test.py`.

Also it appears the change from `http` to `https` has broken the build: https://travis-ci.org/sjkingo/python-freshdesk/builds/69689310

Otherwise nice work I'd love to have the API expanded to support ticket creation.

**Comment by silentninja** [comment]
I ran the tests but it got held up at the second test.So i pushed to see if travis build broke and it didnt show up for few mins.Looks like changing from http to https made the ```test_404_error``` lock up and takes more than 10mins to timeout since ```http://ticketus.org/``` doesn't support ```https```.Can i change the ticketus.org to something else or does it have to limited to ticketus.org

**Comment by sjkingo** [comment]
Should be fine to change - iirc it's simply set to that for testing 404's - as `ticketus.org` is not a valid Freshdesk domain. (it's a project that I have hosted on GH pages)

**Comment by silentninja** [comment]
I am  not sure how to write test for post request.Adding mock library would make it easier to write tests for post requests.I tried creating a file on post requests and appending the sent data to it,but not sure if that  is the way to go.Any ideas on how to proceed further without the mock or can I add mock library as  test requirement

**Pull request closed without merging**
