### PR TITLE
Filter companies

### PR DESCRIPTION
**Pull request by RyanOM**
Hi there,
I've added the possibility of company filtering as mentioned in the docs:
https://developers.freshdesk.com/api/#filter_companies

If anything else is needed, please let me know.
Thanks!

### CODE REVIEW

**Comment by sjkingo** [comment]
This looks great, thanks!

Could you go through and change all of the instances in the codebase of:

```
page = 1 if "page" not in kwargs else kwargs["page"]
per_page = 100 if "per_page" not in kwargs else kwargs["per_page"]
```

to:

```
page = kwargs.get("page", 1)
per_page = kwargs.get("per_page", 100)
```

for consistency.

I noticed it in a PR yesterday but didn't realise there were more in the existing code.

Thanks!

**Comment by RyanOM** [comment]
Sorry about that.
I've updated the PR. Let me know if something else needs adjusted

**Comment by sjkingo** [comment]
Not at all, just thought it was a good time to change that :-)

**Comment by sjkingo** [comment]
Released as 1.3.2 on pypi

**Comment by RyanOM** [comment]
Awesome, thanks again!

**Pull request merged**
