### PR TITLE
Add support for v2 API

### PR DESCRIPTION
**Pull request by andybotting**
This pull request includes change to:
 - Support tox testing to perform testing against multiple scenarios (e.g. flake8, py27 and py35)
 - Refactor original code into a v1 directory and add an API selection compatibility layer
 - Add v2 API framework, to initially support a subset of the resources available:
  * Ticket (list, get, create, update, delete)
  * Comment (list, create replies and notes)
  * Groups (list, get)

Also included is some work for Contacts and Customers, but this is untested.

### CODE REVIEW

**Comment by sjkingo** [comment]
Andy this looks great - thank you!

Would you be able to push some documentation to `README.md` on this branch also for the API versions? Just something simple showing how to switch, what's supported etc.

Thanks

**Comment by andybotting** [comment]
Great. Now I know you're happy with them, I'll update the doc soon and send
it over

**Comment by andybotting** [comment]
Now with super cool docs :dancers:

**Comment by andybotting** [comment]
Hey @sjkingo Had a chance to look this over?

**Comment by sjkingo** [comment]
Sorry Andy I've been crazy busy. I'll try and have a look tonight or tomorrow and merge it in.

**Comment by andybotting** [comment]
Absolutely no hurry mate

**Comment by sjkingo** [comment]
I've merged this now - great work and thank you.

I will do a version bump and publish to PyPi. Do you think this is a big enough and complete change to bump to version 1.0.0?

**Comment by andybotting** [comment]
Yeah, you're at 0.9.4 right now so I would think 1.0.0 would be a good choice

**Comment by sjkingo** [comment]
Version 1.0.0 released on pypi.. thanks so much for the work

**Comment by andybotting** [comment]
My pleasure ;)

**Pull request merged**
