### PR TITLE
Added models for cutomers and time entries

### PR DESCRIPTION
**Pull request by fstolba**
also, modified _to_timestamp() to work with builtin datetime module to be able to use the generated timestamps directly with sqlalchemy datetime type.

### CODE REVIEW

**Comment by sjkingo** [comment]
Looks good, but could you fix the exception here:

https://travis-ci.org/sjkingo/python-freshdesk/jobs/74624896

I can't remember the reason for using `dateutil` instead of `datetime`, but I'm sure I wouldn't have used it without a valid reason so we need to be sure nothing breaks by reverting to the builtin module :)

**Comment by fstolba** [comment]
of course, it's fixed now.
I oversaw commit 56d9a4848cf2634426223538cf8096b1e064772f where the change from datetime to dateutil was introduced. Looks much cleaner using dateutil. Calling the .parse() method on the parser object also returns a datetime object so that should be fine.

**Comment by sjkingo** [comment]
Great, thanks! Are you also able to add some tests for this too?

**Comment by fstolba** [comment]
I think those should cover most of it.

**Comment by sjkingo** [comment]
That's great, I've merged it now and will push it to PyPi shortly.

Thanks so much!

**Comment by sjkingo** [comment]
All done - I've pushed it to PyPi as 0.9.4 and also pushed a wheel for installation

**Comment by fstolba** [comment]
Very nice, thanks to you too for updating the readme

**Pull request merged**
