### PR TITLE
Create ticket v1

### PR DESCRIPTION
**Pull request by prenit-coverfox**
Added api wrapper for create_ticket method in freshdesk api version 1.
Changed API class methods like _get() and _post()

added create_contact method in v1 and v2

### CODE REVIEW

**Comment by prenit-coverfox** [comment]
Yes. I am taken in by some other work. Will add test cases and fix the issue in few days.

**Comment by prenit-coverfox** [comment]
@sjkingo I have fixed the test cases and added new tests for my changes. Can you please review and merge this fast? We need to use this library on urgent basis and we dont want to use custom forks.

**Comment by sjkingo** [comment]
That's great, thank you. I'll merge and release new version today.

**Comment by prenit-coverfox** [comment]
@sjkingo Will you be able to take this on priority? Much appreciated

**Comment by sjkingo** [comment]
Apologies for the delay, I have merged these changes and released 1.2.0 on pypi. Thanks for the work!

**Pull request merged**
