### PR TITLE
Feat/solutions

### PR DESCRIPTION
**Pull request by xtof2all**
Adding the feature the get solution categories, solution folders and articles. It is also possible to retrieve them in another language. For now, this is only the list/get operation. 

I have directly added some test cases as well

### CODE REVIEW

**Comment by sjkingo** [comment]
Hi, it looks like you've changed the permissions on test.sh from 755 to 644, making it unexecutable by Travis. Could you please fix and force push? Thanks!

**Comment by xtof2all** [comment]
Strangely, the test fail, while they were okay locally. It seems to be a problem with the encoding as I'm testing for accented characters in the translation. I will first test with by specify encoding as described in [https://www.python.org/dev/peps/pep-0263/]. If this does not work, I will eliminate the accents in the tests.

**Comment by xtof2all** [comment]
@coveralls It seems that the tests for the python2.7 were failing. Finally, I could solve it by explicitly setting the literals in test_solutions.py to be unicode.

**Comment by sjkingo** [comment]
> @coveralls It seems that the tests for the python2.7 were failing. Finally, I could solve it by explicitly setting the literals in test_solutions.py to be unicode.

I'm wondering if a better solution is to keep them as string literals (no `u` prefix), but add this to the top:

```
from __future__ import unicode_literals
```

Do you want to try that?

**Comment by xtof2all** [comment]
@sjkingo Good idea! I have adapted the code such that it uses the future package for the test_solutions.py

**Comment by xtof2all** [comment]
Can you verify whether the approach with the unicode_literal from the __future__ package the correct one?

**Comment by sjkingo** [comment]
Thanks, this looks great! I'll release on pypi later today.

**Pull request merged**
